// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwIOgMFp7PsuJ5BB8x7Q5PXLZHdoHRV8I',
    appId: '1:124746510264:web:ab622acb326727ce1ee94d',
    messagingSenderId: '124746510264',
    projectId: 'flutterbloc-97b7f',
    authDomain: 'flutterbloc-97b7f.firebaseapp.com',
    storageBucket: 'flutterbloc-97b7f.appspot.com',
    measurementId: 'G-1SQ8SDQRKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnkqz_6D-Ltg2DH1mssIY6aGCnMnGNYVk',
    appId: '1:124746510264:android:bbe61a68681183e81ee94d',
    messagingSenderId: '124746510264',
    projectId: 'flutterbloc-97b7f',
    storageBucket: 'flutterbloc-97b7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDio_2SyqFffAayRVRkDZKON82pP49Z1kY',
    appId: '1:124746510264:ios:0af51f8c0330f7511ee94d',
    messagingSenderId: '124746510264',
    projectId: 'flutterbloc-97b7f',
    storageBucket: 'flutterbloc-97b7f.appspot.com',
    iosBundleId: 'com.example.flutterTutoBlc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDio_2SyqFffAayRVRkDZKON82pP49Z1kY',
    appId: '1:124746510264:ios:0af51f8c0330f7511ee94d',
    messagingSenderId: '124746510264',
    projectId: 'flutterbloc-97b7f',
    storageBucket: 'flutterbloc-97b7f.appspot.com',
    iosBundleId: 'com.example.flutterTutoBlc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwIOgMFp7PsuJ5BB8x7Q5PXLZHdoHRV8I',
    appId: '1:124746510264:web:7ce1bfa24d93660b1ee94d',
    messagingSenderId: '124746510264',
    projectId: 'flutterbloc-97b7f',
    authDomain: 'flutterbloc-97b7f.firebaseapp.com',
    storageBucket: 'flutterbloc-97b7f.appspot.com',
    measurementId: 'G-XCNQ9NM3GV',
  );
}
